services:
  nodejs-service:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: nodejs-container
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app/node
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: incredidose
    restart: unless-stopped # Restart node js when host machine restarts

  apache-service:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - ./includes:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: "%" 
      MYSQL_DATABASE: incredidose
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306     
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql-data:
